name: cli_launcher_example
version: 0.0.0
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

executables:
  example:

cli_launcher:
  example:
    launcherFile: package:cli_launcher_example/src/launcher.dart
    launcherClass: ExampleLauncher

dependencies:
  cli_launcher: ^0.1.1

dev_dependencies:
  test: ^1.21.6
