name: cli_launcher
description:
  CLI development utility to support launching of locally installed versions.
version: 0.0.0
repository: https://github.com/blaugold/cli_launcher
issue_tracker: https://github.com/blaugold/cli_launcher/issues

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  path: ^1.8.2
  pubspec_parse: ^1.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
