name: cli_launcher
description:
  CLI development utility to support launching locally installed versions.
version: 0.3.2
repository: https://github.com/blaugold/cli_launcher
issue_tracker: https://github.com/blaugold/cli_launcher/issues

environment:
  sdk: ^3.8.0

dependencies:
  path: ^1.8.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
  melos: ^6.3.3
  daco: ^0.4.0
