name: cli_launcher
description:
  CLI development utility to support launching locally installed versions.
version: 0.1.1
repository: https://github.com/blaugold/cli_launcher
issue_tracker: https://github.com/blaugold/cli_launcher/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cli_util: ^0.3.5
  package_config: ^2.1.0
  path: ^1.8.2
  pubspec_parse: ^1.2.1
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
