name: cli_launcher_example_flutter_workspace
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.0

executables:
  example_flutter_workspace:

dependencies:
  cli_launcher:
    path: ../../../..
