name: CI

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ci:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dart: [stable, dev]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.dart }}
      - run: dart pub global activate melos
      - run: dart pub global activate daco
      - run: melos bootstrap
      - run: melos format:check
      - run: melos analyze
      - run: melos run activate_example_cli
      - run: melos test
